"""
phase2.models.verification_report
==================================
The final detailed structural report generated by the Verification Agent.
"""
from enum import Enum
from typing import List
from pydantic import BaseModel, Field

from phase2.models.evidence_score import EvidenceScore
from phase2.models.validation_metrics import ValidationMetrics


class VerificationStatus(str, Enum):
    PASSED = "passed"
    DEGRADED = "degraded"
    FAILED = "failed"


class VerificationWarning(BaseModel):
    """Structured warning for verification constraints."""
    warning_code: str = Field(..., description="Unique error code identifier.")
    severity: str = Field(..., description="E.g., Low, Medium, High")
    message: str = Field(..., description="Human-readable warning context.")
    chunk_id: str | None = Field(default=None, description="Optional associated chunk")


class VerificationReport(BaseModel):
    """
    Detailed verification report providing reasoning agents with absolute clarity
    regarding evidence boundaries, capabilities, and constraints.
    """
    verification_status: VerificationStatus = Field(
        ..., description="Overall verification outcome."
    )
    evidence_quality_summary: str = Field(
        default="Pending", description="Categorical evaluation of the chunk cohort."
    )
    evidence_completeness_summary: str = Field(
        default="Pending", description="Semantic threshold completeness evaluation."
    )
    citation_status_summary: str = Field(
        default="Pending", description="Categorical evaluation of citation integrity."
    )
    metadata_quality_summary: str = Field(
        default="Pending", description="Categorical evaluation of structured constraints."
    )
    
    warnings: List[VerificationWarning] = Field(
        default_factory=list, description="Non-fatal violations caught during checks."
    )
    recommendations: List[str] = Field(
        default_factory=list, description="Machine-readable directives for the Reasoning Agent."
    )
    evidence_scores: List[EvidenceScore] = Field(
        default_factory=list, description="Granular scoring per retrieved chunk."
    )
    validation_metrics: ValidationMetrics = Field(
        ..., description="Raw metric aggregations from the check passes."
    )
