"use client"

import React, { useState } from 'react'
import { motion, AnimatePresence } from 'motion/react'
import { FileText, ChevronRight, CheckCircle2 } from 'lucide-react'

const MOCK_DOCUMENTS = [
  {
    id: 1,
    title: "LIC's Bima Jyoti (Plan No. 860)",
    type: "Policy Document",
    page: 4,
    excerpt: "Guaranteed Additions at the rate of Rs. 50 per thousand Basic Sum Assured will be added to the policy at the end of each policy year.",
    answer: "The Bima Jyoti policy provides a Guaranteed Addition of Rs. 50 per thousand Basic Sum Assured at the end of every policy year."
  },
  {
    id: 2,
    title: "IRDAI Health Insurance Regulations",
    type: "Regulatory Document",
    page: 12,
    excerpt: "All health insurance policies shall provide a grace period of 30 days for payment of renewal premium.",
    answer: "You have a 30-day grace period to pay your renewal premium without losing your health insurance coverage."
  },
  {
    id: 3,
    title: "LIC Jeevan Umang Terms",
    type: "Terms & Conditions",
    page: 8,
    excerpt: "The loan facility shall be available after payment of premiums for at least two full years.",
    answer: "You can apply for a policy loan only after you have paid the full premiums for at least two consecutive years."
  }
]

export function EvidenceExplorer() {
  const [activeDoc, setActiveDoc] = useState(0)

  return (
    <section id="sources" className="relative py-32 bg-background overflow-hidden">
      <div className="container max-w-6xl mx-auto px-4">
        
        <div className="text-center mb-24 space-y-4">
          <motion.h2 
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="text-3xl md:text-5xl font-bold tracking-tight"
          >
            See where the answer comes from.
          </motion.h2>
          <motion.p
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ delay: 0.1 }}
            className="text-lg text-muted-foreground max-w-2xl mx-auto"
          >
            Every answer generated by Aegis Audit is strictly tied to an available source document. 
            No hallucinations. Just verifiable intelligence.
          </motion.p>
        </div>

        <div className="flex flex-col lg:flex-row gap-12 items-center">
          
          {/* Left: AI Answer & Connection */}
          <div className="w-full lg:w-1/2 flex flex-col gap-8">
            <AnimatePresence mode="wait">
              <motion.div
                key={activeDoc}
                initial={{ opacity: 0, x: -20 }}
                animate={{ opacity: 1, x: 0 }}
                exit={{ opacity: 0, x: 20 }}
                transition={{ duration: 0.3 }}
                className="glass rounded-3xl p-8 border border-border/50 relative shadow-2xl"
              >
                <div className="flex items-center gap-3 mb-6">
                  <div className="size-8 rounded-full bg-primary/20 flex items-center justify-center">
                    <CheckCircle2 className="size-5 text-primary" />
                  </div>
                  <span className="font-semibold text-primary uppercase tracking-wider text-sm">Grounded Answer</span>
                </div>
                
                <p className="text-xl md:text-2xl text-foreground leading-relaxed font-medium">
                  "{MOCK_DOCUMENTS[activeDoc].answer}"
                </p>

                {/* Connecting Line to Right Side (Desktop) */}
                <div className="hidden lg:block absolute top-1/2 -right-12 w-12 h-[1px] bg-primary/50 border-t border-dashed border-primary/50" />
              </motion.div>
            </AnimatePresence>
          </div>

          {/* Right: Document Stack Explorer */}
          <div className="w-full lg:w-1/2 relative h-[450px]">
            {MOCK_DOCUMENTS.map((doc, index) => {
              const isActive = index === activeDoc
              const offset = index - activeDoc
              const yPos = offset * 20
              const scale = 1 - Math.abs(offset) * 0.05
              const zIndex = 30 - Math.abs(offset)
              const opacity = 1 - Math.abs(offset) * 0.3

              return (
                <motion.div
                  key={doc.id}
                  onClick={() => setActiveDoc(index)}
                  animate={{ 
                    y: isActive ? 0 : yPos + 100, 
                    scale: isActive ? 1 : scale, 
                    zIndex,
                    opacity
                  }}
                  transition={{ type: "spring", stiffness: 300, damping: 30 }}
                  className={`absolute left-0 right-0 p-6 rounded-2xl border transition-all cursor-pointer ${
                    isActive 
                      ? 'bg-card border-primary/40 shadow-[0_10px_40px_-10px_rgba(var(--primary),0.3)]' 
                      : 'bg-card/50 border-border/30 hover:border-border hover:bg-card/80'
                  }`}
                  style={{ top: '20%' }}
                >
                  <div className="flex items-center justify-between mb-4">
                    <div className="flex items-center gap-3">
                      <div className={`p-2 rounded-lg ${isActive ? 'bg-primary/10 text-primary' : 'bg-muted text-muted-foreground'}`}>
                        <FileText className="size-5" />
                      </div>
                      <div>
                        <h4 className={`font-semibold ${isActive ? 'text-foreground' : 'text-muted-foreground'}`}>{doc.title}</h4>
                        <span className="text-xs text-muted-foreground uppercase tracking-wider">{doc.type} • Page {doc.page}</span>
                      </div>
                    </div>
                    {isActive && <ChevronRight className="text-primary size-5" />}
                  </div>

                  <AnimatePresence>
                    {isActive && (
                      <motion.div
                        initial={{ opacity: 0, height: 0 }}
                        animate={{ opacity: 1, height: 'auto' }}
                        exit={{ opacity: 0, height: 0 }}
                        className="mt-6 pt-4 border-t border-border/50 overflow-hidden"
                      >
                        <span className="text-xs font-mono text-muted-foreground mb-2 block">SOURCE EXCERPT</span>
                        <div className="bg-muted/50 rounded-lg p-4 border border-border/50 font-serif italic text-muted-foreground">
                          "{doc.excerpt}"
                        </div>
                      </motion.div>
                    )}
                  </AnimatePresence>
                </motion.div>
              )
            })}
          </div>

        </div>
      </div>
    </section>
  )
}
